# Generated by Django 3.2.7 on 2021-12-14 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='address1',
        ),
    ]
