# Generated by Django 3.2.7 on 2021-12-14 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_contact_address1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='password',
        ),
    ]
