# Generated by Django 3.2.7 on 2021-12-14 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_contact_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='LastName',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='contact',
            name='Name',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='contact',
            name='city',
            field=models.CharField(default='', max_length=120),
        ),
    ]
