# Generated by Django 3.2.7 on 2021-12-14 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20211214_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='LastName',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='Name',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='city',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
